### ISSUE TITLE
No options to freeze column from right side RTL

### ISSUE THREAD

**Issue by dishankEbizz** [BTAProgrammers/SpreadsheetView#1]
Currently possible to freeze the column from first.

Is it possible to freeze the column from the last?

**Comment by FadyFaheem** [comment]
I will be adding to my ToDo.Md file. Currently not possible, but will be definitely adding this as an option.

**Comment by dishankEbizz** [comment]
@FadyFaheem 
![Timetable](https://user-images.githubusercontent.com/69805613/217148863-45ebb8a8-d659-41f7-9c41-e866edcd4cc3.png)
I need to freeze the column from the right side. just like the attached image.

**Comment by FadyFaheem** [comment]
Do you ned to have them frozen on both sides?

**Comment by dishankEbizz** [comment]
> 
one direction at a time will be helpful. means bool to inverse freeze direction also can be useful.
